language: node_js
sudo: false
node_js:
  - "6"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - wget https://github.com/rhadamanthe/host-grabber-pp/blob/master/src/scripts/mixed/library.dictionary.js
  - echo "module.exports.parseAndVerifyDictionary = parseAndVerifyDictionary;" >> library.dictionary.js

script:
  - cd build
  - npm install
  - npm start
